### ISSUE TITLE
Could you make a Plugin for selfhosted alternative of Teslafi called Teslamate?

### ISSUE THREAD

**Issue by Heggeg** [f00d4tehg0dz/Teslafi-Status-Plugin-for-Eglato-Streamdeck#1]
Could you make a Plugin for selfhosted alternative of Teslafi called Teslamate?

https://github.com/adriankumpf/teslamate

**Comment by f00d4tehg0dz** [comment]
hey @Heggeg let me look through it over the coming weeks and get back to you! never heard of teslamate. seems awesome!

**Comment by f00d4tehg0dz** [comment]
Hi @Heggeg, I apologize for the long wait here. I've been refactoring and adding new features to the Plugin.  Is this something you still require integrated??
