### ISSUE TITLE
Problem with multiple vehicles

### ISSUE THREAD

**Issue by cscashby** [f00d4tehg0dz/Teslafi-Status-Plugin-for-Eglato-Streamdeck#4]
I have two linked TeslaFi accounts, both linked in a fleet.

If I generate a key using one it works fine, but when I generate a key using the other account (either logged in clean or linked via the fleet menu item) I get 'Poor Connection Updating API Rate Limit'

They are both completely different keys.

**Comment by matthiasg** [comment]
I have the same issue :(

**Comment by f00d4tehg0dz** [comment]
> I have two linked TeslaFi accounts, both linked in a fleet.
> 
> If I generate a key using one it works fine, but when I generate a key using the other account (either logged in clean or linked via the fleet menu item) I get 'Poor Connection Updating API Rate Limit'
> 
> They are both completely different keys.

While I don't have a second vehicle. I should be able to test this with some dummy data. I'll take a look this weekend and get back to you. Sorry about this guys!

**Comment by f00d4tehg0dz** [comment]
Hi @cscashby  and @matthiasg , I've been able to get some time free to refactor and add new features to this plugin. Unfortunately, I do not have more than one Tesla vehicle. However, if one of you can pass over a `test.json` with dummy data, I can work with that. I'm just unclear on how the Tesla FI API JSON outputs when it's multiple vehicles. 

I'm providing a sample `test.json` to give you both an idea of what I'm utilizing in the TeslaFI plugin update.

```
{
    "data_id": 1111111,
    "Date": "2024-05-17 20:58:25",
    "display_name": "xxxx",
    "battery_range": "111.1",
    "charging_state": "xxxx",
    "inside_temp": "11.0",
    "outside_temp": "11.1",
    "odometer": "11111.11111"
}
```

**Comment by matthiasg** [comment]
@f00d4tehg0dz what should we do exactly ?

**Comment by cscashby** [comment]
I'm sorry I no longer have both vehicles so I can't help here.

**Comment by f00d4tehg0dz** [comment]
> I'm sorry I no longer have both vehicles so I can't help here.

No problem! Sorry for not getting this done much earlier. Life and priorities got in the way unfortunately.

**Comment by f00d4tehg0dz** [comment]
> @f00d4tehg0dz what should we do exactly ?

I understand you have two different API Keys; is that correct? Initially, I thought you both had one API key that outputs multiple vehicles for your fleet.  But if it's just adding multiple Teslafi API keys, I can also do that. I'm assuming you'd want to dynamically add as many API keys as you want, and you add a tile for each API key(if possible). Or would you like a singular tile to rotate through every vehicle via a timer based on their API key?

**Comment by matthiasg** [comment]
Best would be to https://www.tesla.com/developer-docs

See https://developer.tesla.com/docs/fleet-api

I have one account for both cars , but in a family it's possible one could have two accounts and thus two api keys

**Comment by f00d4tehg0dz** [comment]
> Best would be to https://www.tesla.com/developer-docs
> 
> See https://developer.tesla.com/docs/fleet-api
> 
> I have one account for both cars , but in a family it's possible one could have two accounts and thus two api keys

Got it Thank you! 
In addition to supporting multiple cars with TeslaFi, I'm also adding support for Teslamate. I'll peek through the Tesla developer docs to see how they handle things and then check through TeslaFi, I have no idea why I didn't think that. 🤦  
Unfortunately, I am dealing with an issue with MQTT and the WebSocket rejecting me for Teslamate, so I just need to get TrueNas all sorted with those pods.  

**Previews**

TeslaFI
![image](https://github.com/f00d4tehg0dz/Teslafi-Status-Plugin-for-Eglato-Streamdeck/assets/1635526/8fd2dbf0-e2f6-4eb6-959b-032930e1b09c)

Teslamate
![image](https://github.com/f00d4tehg0dz/Teslafi-Status-Plugin-for-Eglato-Streamdeck/assets/1635526/445b13f0-0e37-4a76-bfdf-a6e5cac72505)

**Comment by f00d4tehg0dz** [comment]
All resolved.
